[workspace]
authors = ["shivasankar <shivasankar.ka@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly/",
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[package]
name = "scijo"
version = "0.2.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.*"}

[package.build.config.pkg]
name = "scijo"

[package.host-dependencies]
modular = ">=26.2.0.dev2026021805,<27"

[package.build-dependencies]
modular = ">=26.2.0.dev2026021805,<27"
numojo = { git = "https://github.com/shivasankarka/NuMojo.git", branch = "refcounting"}

[package.run-dependencies]
modular = ">=26.2.0.dev2026021805,<27"
numojo = { git = "https://github.com/shivasankarka/NuMojo.git", branch = "refcounting"}

[dependencies]
modular = ">=26.2.0.dev2026021805,<27"
numojo = { git = "https://github.com/shivasankarka/NuMojo.git", branch = "refcounting"}
python = ">=3.14.3,<3.15"

[tasks]
format = "mojo format ./scijo && mojo format ./tests && mojo format ./benchmark"
tests = "pixi run package && bash tests/test_all.sh"
build = "mojo build"
package = "mojo package scijo && cp scijo.mojopkg tests/"
