[workspace]
authors = ["shivasankar <shivasankar.ka@gmail.com>"]
channels = [
    "https://conda.modular.com/max",
    "https://prefix.dev/conda-forge",
    "https://prefix.dev/modular-community"
]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[package]
name = "scijo"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.*"}

[package.build.config.pkg]
name = "scijo"

[package.host-dependencies]
modular = ">=25.6.1,<26"

[package.build-dependencies]
modular = ">=25.6.1,<26"
numojo = { git = "https://github.com/shivasankarka/NuMojo.git", branch = "gpu_ndarray"}
# numojo = { path = "/Users/shivasankar/Documents/Codes/NuMojo"}

[package.run-dependencies]
modular = ">=25.6.1,<26"
numojo = { git = "https://github.com/shivasankarka/NuMojo.git", branch = "gpu_ndarray"}
# numojo = { path = "/Users/shivasankar/Documents/Codes/NuMojo"}

[dependencies]
# These deps are needed for local development, mojo test, language server, etc
modular = ">=25.6.1,<26"
numojo = { git = "https://github.com/shivasankarka/NuMojo.git", branch = "gpu_ndarray"}

[tasks]
format = "mojo format ./"
test = "mojo test -I . tests/"
build = "mojo build"
package = "mojo package scijo"
